spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_management
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  security:
    user:
      name: admin
      password: admin123
